import math
width=float(input ('ความกว้างของกล่อง (เมตร):'))
length=float(input ('ความยาวของกล่อง (เมตร):'))
height=float(input('ความสูงของกล่อง (เมตร):'))
area=2*(width*height+length*height)
paint=math.ceil(area/5)
print('กล่องขนาดกว้าง {:.2f} เมตร ยาว {:.2f} เมตร สูง {:.2f} เมตร'.format(width,length,height))
print('ใฃ้จำนวนสี {} แกลลอน'.format(paint))
print(f'กล่องขนาดกว้าง {width:.2f} เมตร ยาว {length:.2f} เมตร สูง {height:.2f} เมตร')
print(f'ใช้จำนวนสี {paint} แกลลอน')
print('กล่องขนาดกว้าง',f'{width:.2f}','เมตร','ยาว',f'{length:.2f}','เมตร','สูง',f'{height:.2f}','เมตร')
print('ใช้จำนวนสี',f'{paint:.2f}','แกลลอน')
print('กล่องขนาดกว้าง '+f'{width:.2f}'+' เมตร '+'ยาว '+f'{length:.2f}'+' เมตร'+' สูง '+f'{height:.2f}'+' เมตร')
print('ใช้จำนวนสี'+f' {paint:.2f}'+' แกลลอน')
print('กล่องขนาดกว้าง %.2f เมตร ยาว %.2f เมตร สูง %.2f เมตร' %(width,length,height))
print('ใช้จำนวนสี %.2f แกลลอน'%(paint))